name: hezmaa
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
 
  smooth_page_indicator: ^1.2.0
  intl_phone_field: ^3.2.0
  flutter_otp_text_field: ^1.1.3+2
  curved_labeled_navigation_bar: ^2.0.2
  
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.7.0
  geocoding: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.3.0
  intl_phone_number_input: ^0.7.4
  flutter_slidable: ^3.1.1
  go_router: ^14.2.3
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  geolocator: ^12.0.0
  google_places_flutter: ^2.0.9
  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_rating_bar: ^4.0.0 
  step_progress_indicator: ^1.0.2
  order_tracker: ^0.0.2
  http: ^0.13.6
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  flutter_pannable_rating_bar: ^2.7.2+1
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^9.2.2
  intl: ^0.19.0
  faker: ^2.1.0
  image_picker: ^1.1.2
  flutter_screenutil: ^5.9.3
  permission_handler: ^10.0.0
  cached_network_image: ^3.1.0
  
  

  
  
  
  

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
    
    - assets/icons/

  fonts:
    - family: STVBold
      fonts:
        - asset: assets/fonts/STVBold.ttf
