// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIExWGKPSxHLloJkFBTApiMCBWNhLDTE0',
    appId: '1:181458785821:web:fc52597ff1c357dcf858f4',
    messagingSenderId: '181458785821',
    projectId: 'hezma-519c7',
    authDomain: 'hezma-519c7.firebaseapp.com',
    storageBucket: 'hezma-519c7.appspot.com',
    measurementId: 'G-77RV4RMB8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC0It-saBw0qVJP4qg3DGGwjUuLtEOBPo',
    appId: '1:181458785821:android:09c6b76c80205879f858f4',
    messagingSenderId: '181458785821',
    projectId: 'hezma-519c7',
    storageBucket: 'hezma-519c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYV8U2gVURmc6eZoOWL9WMi-f4speepR0',
    appId: '1:181458785821:ios:5cf6efee939b73b6f858f4',
    messagingSenderId: '181458785821',
    projectId: 'hezma-519c7',
    storageBucket: 'hezma-519c7.appspot.com',
    iosBundleId: 'com.ali.hezma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYV8U2gVURmc6eZoOWL9WMi-f4speepR0',
    appId: '1:181458785821:ios:b65b0a809b8883b3f858f4',
    messagingSenderId: '181458785821',
    projectId: 'hezma-519c7',
    storageBucket: 'hezma-519c7.appspot.com',
    iosBundleId: 'com.example.hezma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIExWGKPSxHLloJkFBTApiMCBWNhLDTE0',
    appId: '1:181458785821:web:a3401166d5b98dfff858f4',
    messagingSenderId: '181458785821',
    projectId: 'hezma-519c7',
    authDomain: 'hezma-519c7.firebaseapp.com',
    storageBucket: 'hezma-519c7.appspot.com',
    measurementId: 'G-J39CVKQXNH',
  );
}
